/** LTY.LTD supported marques (Europe + UK) — fixed brand list + model lineups for dropdowns. */

export const PART_CATEGORIES = [
  "Engine Parts",
  "Brake System",
  "Suspension",
  "Electrical",
  "Body Parts",
  "Interior",
  "Transmission",
  "Cooling System",
  "Exhaust",
  "Steering",
] as const

/**
 * Canonical brand keys used in URLs and dropdowns (matches customer list).
 * VW / Skoda / MINI / DS spelling kept consistent here.
 */
export const MODELS_BY_BRAND: Record<string, string[]> = {
  Lotus: [
    "Elise",
    "Exige",
    "Evora",
    "Emira",
    "Eletre",
    "Esprit",
    "Europa",
  ],
  "Land Rover": [
    "Defender",
    "Discovery",
    "Discovery Sport",
    "Freelander",
    "Freelander 2",
    "Range Rover",
    "Range Rover Evoque",
    "Range Rover Sport",
    "Range Rover Velar",
  ],
  Jaguar: [
    "XE",
    "XF",
    "XJ",
    "X-Type",
    "S-Type",
    "F-Pace",
    "E-Pace",
    "I-Pace",
    "F-Type",
  ],
  MINI: [
    "Hatch",
    "Cooper",
    "Cooper S",
    "Clubman",
    "Countryman",
    "Paceman",
    "Coupe",
    "Roadster",
    "Electric",
  ],
  Vauxhall: [
    "Adam",
    "Astra",
    "Cascada",
    "Combo",
    "Corsa",
    "Corsa-e",
    "Crossland",
    "Grandland",
    "Insignia",
    "Meriva",
    "Mokka",
    "Movano",
    "Vectra",
    "Vivaro",
    "Zafira",
  ],
  VW: [
    "Amarok",
    "Arteon",
    "Beetle",
    "Caddy",
    "Golf",
    "ID.3",
    "ID.4",
    "ID.5",
    "ID.7",
    "Jetta",
    "Passat",
    "Polo",
    "Scirocco",
    "Sharan",
    "T-Cross",
    "T-Roc",
    "Tiguan",
    "Touran",
    "Touareg",
    "Transporter",
    "Up!",
  ],
  Audi: [
    "A1",
    "A3",
    "A4",
    "A5",
    "A6",
    "A7",
    "A8",
    "Q2",
    "Q3",
    "Q4 e-tron",
    "Q5",
    "Q7",
    "Q8",
    "TT",
    "e-tron",
    "RS3",
    "RS4",
    "RS5",
    "RS6",
    "RS7",
    "S3",
    "S4",
    "S5",
    "S6",
    "S7",
    "S8",
  ],
  Skoda: [
    "Citigo",
    "Fabia",
    "Scala",
    "Octavia",
    "Superb",
    "Kamiq",
    "Karoq",
    "Kodiaq",
    "Enyaq",
  ],
  SEAT: [
    "Mii",
    "Ibiza",
    "Leon",
    "Arona",
    "Ateca",
    "Tarraco",
    "Toledo",
    "Alhambra",
  ],
  BMW: [
    "1 Series",
    "2 Series",
    "3 Series",
    "4 Series",
    "5 Series",
    "6 Series",
    "7 Series",
    "8 Series",
    "X1",
    "X2",
    "X3",
    "X4",
    "X5",
    "X6",
    "X7",
    "Z4",
    "i3",
    "i4",
    "i5",
    "i7",
    "iX",
    "M2",
    "M3",
    "M4",
    "M5",
  ],
  "Mercedes-Benz": [
    "A-Class",
    "B-Class",
    "C-Class",
    "CLA",
    "CLS",
    "E-Class",
    "S-Class",
    "GLA",
    "GLB",
    "GLC",
    "GLE",
    "GLS",
    "G-Class",
    "V-Class",
    "Sprinter",
    "AMG GT",
  ],
  Renault: [
    "Arkana",
    "Austral",
    "Captur",
    "Clio",
    "Espace",
    "Kadjar",
    "Kangoo",
    "Laguna",
    "Master",
    "Megane",
    "Scenic",
    "Trafic",
    "Twingo",
    "Zoe",
  ],
  Peugeot: [
    "208",
    "308",
    "508",
    "2008",
    "3008",
    "5008",
    "Partner",
    "Expert",
    "Rifter",
    "Traveller",
  ],
  "Citroën": [
    "Berlingo",
    "C3",
    "C4",
    "C5",
    "C5 Aircross",
    "C5 X",
    "SpaceTourer",
  ],
  DS: ["DS 3", "DS 4", "DS 7", "DS 9"],
  Fiat: ["500", "500L", "500X", "Doblo", "Ducato", "Panda", "Punto", "Tipo"],
  "Alfa Romeo": ["Giulia", "Giulietta", "MiTo", "Stelvio", "Tonale", "159", "Brera"],
  Volvo: ["C40", "EX30", "EX90", "S60", "S90", "V40", "V60", "V90", "XC40", "XC60", "XC90"],
  Dacia: ["Duster", "Jogger", "Lodgy", "Logan", "Sandero", "Sandero Stepway"],
}

/**
 * Marques that must never appear in brand dropdowns, search filters, quote selects, or footer links.
 * Kept as an explicit deny-list so removed brands stay out of the UI even if `MODELS_BY_BRAND` is edited.
 */
export const BRANDS_EXCLUDED_FROM_UI = [
  "Morgan",
  "Porsche",
  "MG",
  "TVR",
] as const

/** Exact brand list for all dropdowns (alphabetical). Same keys as supported {@link MODELS_BY_BRAND} entries, minus {@link BRANDS_EXCLUDED_FROM_UI}. */
export const EU_UK_BRANDS = Object.keys(MODELS_BY_BRAND)
  .filter(
    (name) =>
      !(BRANDS_EXCLUDED_FROM_UI as readonly string[]).includes(name),
  )
  .sort((a, b) => a.localeCompare(b))

/**
 * Logo image URLs for the “All Partner Brands” carousel. Keys match {@link MODELS_BY_BRAND} / {@link EU_UK_BRANDS}.
 * Mix of SVG / PNG / JPG from Wikimedia Commons or English Wikipedia uploads (varies per marque).
 */
export const BRAND_LOGO_SVG: Record<string, string> = {
  "Alfa Romeo":
    "https://upload.wikimedia.org/wikipedia/en/2/2a/Alfa_Romeo_logo.png",
  Audi: "https://upload.wikimedia.org/wikipedia/commons/9/92/Audi-Logo_2016.svg",
  BMW: "https://upload.wikimedia.org/wikipedia/commons/f/f4/BMW_logo_%28gray%29.svg",
  "Citroën": "https://upload.wikimedia.org/wikipedia/commons/d/dd/Citroen_2022.svg",
  Dacia: "https://upload.wikimedia.org/wikipedia/commons/4/41/Dacia-Logo-2021.svg",
  DS: "https://upload.wikimedia.org/wikipedia/commons/2/2f/DS_Automobiles_2025_wordmark.svg",
  Fiat: "https://upload.wikimedia.org/wikipedia/commons/1/12/Fiat_Automobiles_logo.svg",
  Jaguar: "https://upload.wikimedia.org/wikipedia/commons/5/50/Jaguar_2024.svg",
  "Land Rover": "https://upload.wikimedia.org/wikipedia/commons/c/c2/Land_Rover_2023.svg",
  Lotus:
    "https://upload.wikimedia.org/wikipedia/en/2/2f/Lotus_Cars_logo.svg",
  "Mercedes-Benz":
    "https://upload.wikimedia.org/wikipedia/commons/3/32/Mercedes-Benz_Star_2022.svg",
  MINI: "https://upload.wikimedia.org/wikipedia/commons/e/e9/MINI_logo.svg",
  Peugeot: "https://upload.wikimedia.org/wikipedia/commons/f/f7/Peugeot_Logo.svg",
  Renault: "https://upload.wikimedia.org/wikipedia/commons/a/a5/Renault_2021.svg",
  SEAT: "https://upload.wikimedia.org/wikipedia/commons/f/fc/SEAT_Logo_from_2017.svg",
  Skoda:
    "https://upload.wikimedia.org/wikipedia/commons/5/52/%C5%A0koda_Auto.svg",
  Vauxhall:
    "https://upload.wikimedia.org/wikipedia/en/1/18/Vauxhall_logo_2019.svg",
  Volvo:
    "https://upload.wikimedia.org/wikipedia/commons/2/2b/Volvo_Iron_Mark_-_black.svg",
  VW: "https://upload.wikimedia.org/wikipedia/commons/6/6d/Volkswagen_logo_2019.svg",
}
